### ISSUE TITLE
Privacy Questions

### ISSUE THREAD

**Issue by ghost** [Eclipse-Community/r3dfox-old#14] opened 2024-02-02 17:33 UTC
So I have question, Will the fork be as much about privacy based as lets say waterfox or it will be like floorp, also will it have it's own auto update like waterfox? Thanks in advance for replays.

**Comment by the-r3dacted** [comment] 2024-02-03 11:13
I would like to have that someday, but not currently.

Closing as duplicate of these two issues
https://github.com/Eclipse-Community/r3dfox/issues/6
https://github.com/Eclipse-Community/r3dfox/issues/1

**Closed as not planned by the-r3dacted** 2024-02-03 11:13 UTC
Labels: duplicate
