### ISSUE TITLE
I got this

### ISSUE THREAD

**Issue by Juadiis** [Eclipse-Community/r3dfox-old#156] opened 2024-08-12 13:01 UTC
Here's proof:
![Screenshot_23](https://github.com/user-attachments/assets/64ea67d7-c887-45a3-882f-9e01936f9cb6)

Please fix this

**Comment by the-r3dacted** [comment] 2024-08-12 15:39
Are you using ESU by chance?

**Comment by Juadiis** [comment] 2024-08-12 16:21
> Are you using ESU by chance?

I'm using Windows 7 with Server 2008 R2 update since Server 2008 R2 also has a premium assurance feature. So, still supported on Server 2008/R2 until January, 2026

**Comment by the-r3dacted** [comment] 2024-08-12 16:22
Some ESU update is broken, and I need to eventually get around to fixing.

**Comment by the-r3dacted** [comment] 2024-08-12 16:23
Closing since duplicate of https://github.com/Eclipse-Community/r3dfox/issues/125

**Closed as completed by the-r3dacted** 2024-08-12 16:23 UTC
