### ISSUE TITLE
YouTube video playback broken on 131.0.3

### ISSUE THREAD

**Issue by Jevil7452** [Eclipse-Community/r3dfox-old#195] opened 2024-10-24 14:21 UTC
After updating to this version, YouTube videos stopped playing altogether.
I tested on a new profile and the same occurs there too, so it's not an extension or anything non-default.

**Comment by the-r3dacted** [comment] 2024-10-24 14:25
Tested H.264, VP9, and AV1 video streams and they all work fine for me. Makes no sense as I tested YouTube on various machines without any issues.

**Comment by Jevil7452** [comment] 2024-10-24 14:31
I should've mentioned it earlier, but the OS i use is Windows Vista. Did it also work fine for you in your testing?

**Comment by the-r3dacted** [comment] 2024-10-24 14:41
Huh, I guess this is a Vista only issue then. Well shit.

What is weird is that x86 seems to play video fine. However x86 on Vista x86 crashes after a few seconds.

I'm kinda busy currently, but if you want to test something, try installing Vista extended kernel releases from oldest to newest until the issue gets fixed and tell me the last bad and first good release. From there I can look into what function may be missing and causing the issue.

I hope the Vista x86 issue is related as I can't use this method to test there, and I do not feel like bisecting for a whole day anytime soon.

**Comment by Jevil7452** [comment] 2024-10-24 16:13
I tested it on 7 just now and yes, it is a Vista-only issue. And, I already use the Extended Kernel on my Vista install. The latest version.
On 7 i used the same version of r3dfox and the exact same profile as on Vista.

**Comment by the-r3dacted** [comment] 2024-10-26 00:34
I'm not entirely sure what I did, but it seems to just work now in my testing VM and I have no idea why.

**Comment by the-r3dacted** [comment] 2024-10-26 00:38
Nevermind, I found what I did. I try to disable e10s and multiprocess as much as possible to make debugging easier, and after doing that videos started playing again. I thought I re-enabled everything, but I missed media.allow-audio-non-utility. Setting this to true fixes the issue.

I wonder if this is a sandboxing issue since that is the only major change between x86 and x64.

**Comment by the-r3dacted** [comment] 2024-10-26 01:41
r3dfox x86 crashes seem to be an incompatibility with the VMware x86 graphics drivers. Not sure if worth pursuing.

**Comment by the-r3dacted** [comment] 2024-10-26 07:29
I found the cause of the video issue, now to see if I can fix it without completely undoing it.

**Comment by Jevil7452** [comment] 2024-10-26 07:54
> Nevermind, I found what I did. I try to disable e10s and multiprocess as much as possible to make debugging easier, and after doing that videos started playing again. I thought I re-enabled everything, but I missed media.allow-audio-non-utility. Setting this to true fixes the issue.
> 
> I wonder if this is a sandboxing issue since that is the only major change between x86 and x64.

Thanks, setting the pref mentioned to true fixes the issue.

**Comment by the-r3dacted** [comment] 2024-10-26 07:54
Too sleepy to look into it right now, but I found the specific offending commit.

https://github.com/mozilla/gecko-dev/commit/e75d603c3a0c5c31581d06472b4fa709601068d7

**Comment by the-r3dacted** [comment] 2024-10-28 01:13
So after trying to figure out and decide on a solution, I decided to look up the AppLocker bit referenced in the commit. It's 7+. The old code it replaces also seems to be AppLocker related so I assume it did nothing on Vista as well. Wonder why it was fine until now.

I assume the fix is to make it run on 7+.

**Comment by the-r3dacted** [comment] 2024-10-28 09:30
Fixed in 131.0.3 non-rc

**Closed as completed by the-r3dacted** 2024-10-28 09:30 UTC
