### ISSUE TITLE
Crashing on Win7 ESU FULLY  UPDATED 

### ISSUE THREAD

**Issue by darkalexis1990** [Eclipse-Community/r3dfox-old#125] opened 2024-07-14 11:00 UTC
crashes on latest build on Win7 ESU build 7601.27219 (server2008r2 latest updates throught bypassv12 tool)

![image](https://github.com/user-attachments/assets/f761c8ee-765d-411a-9a86-f21cceed5410)

**Comment by the-r3dacted** [comment] 2024-07-14 11:01
What happens with latest VC++?

https://github.com/abbodi1406/vcredist

**Comment by darkalexis1990** [comment] 2024-07-14 11:02
yes

![image](https://github.com/user-attachments/assets/894c7d96-a205-4097-ae91-d16fb027d8c6)

**Comment by the-r3dacted** [comment] 2024-07-14 11:05
I'm not sure what causes this issue or how I would debug it. I am unable to replicate any crash like this, even with RTM.
Others have reported the same crash before, this is a duplicate of https://github.com/Eclipse-Community/r3dfox/issues/119

**Comment by the-r3dacted** [comment] 2024-07-14 11:06
Since this is a VM, would you be willing to try VxKex?

**Comment by darkalexis1990** [comment] 2024-07-14 11:14
it worked, but its not efficient. also the layout is from win10 which is awful 
![image](https://github.com/user-attachments/assets/1f9b6f1e-e93e-4dff-a312-f0ba32d431c2)

**Comment by darkalexis1990** [comment] 2024-07-14 11:14
the developer must fix this. its a irony to crash on a full updated Win7 ESU machine.

**Comment by the-r3dacted** [comment] 2024-07-14 11:17
Disable reporting as Windows 10 and you'll have the 7 UI

I was actually hoping VxKex wouldn't work so we could test nightly builds to see where it first began, but can't do that.

I actually don't know what causes this, and without knowing the cause, how can I fix it?

**Comment by darkalexis1990** [comment] 2024-07-14 11:19
where is the report crash file in order to send it to you?

**Comment by the-r3dacted** [comment] 2024-07-14 11:20
I would need to somehow replicate the issue myself.

**Comment by the-r3dacted** [comment] 2024-07-20 06:02
Try these builds pls

https://litter.catbox.moe/8wr1wd.7z

**Comment by darkalexis1990** [comment] 2024-07-21 12:05
@K4sum1 it seems to work.

![image](https://github.com/user-attachments/assets/b30542aa-3ec0-4cd5-aa5d-dfdc002f5fc7)

**Comment by the-r3dacted** [comment] 2024-07-21 12:05
Do both work?

**Comment by darkalexis1990** [comment] 2024-07-21 15:25
@K4sum1 yes

**Comment by the-r3dacted** [comment] 2024-07-21 15:27
The only thing that I think could cause the issue is that I've only seen reports like this from non-English localized versions of Windows. What language is your ISO and can you send it pls?

I guess I'll have to look into how Cairo does localization.

**Comment by darkalexis1990** [comment] 2024-07-21 17:12
my ISO is en-US .its a Gen2 ISO release from 9/23

**Comment by the-r3dacted** [comment] 2024-07-21 17:13
Well, you seem to have changed localization then. What are you using?

**Comment by darkalexis1990** [comment] 2024-07-21 17:21
![image](https://github.com/user-attachments/assets/c63b057e-43b0-4d2d-8999-d05822f35885)
![image](https://github.com/user-attachments/assets/67b69e02-24f4-4783-881c-3abac4c97faa)
![image](https://github.com/user-attachments/assets/c942ffcd-cc78-4a67-be92-ca064a2901b2)

**Comment by the-r3dacted** [comment] 2024-07-21 17:41
So I applied those settings and it works fine on my end. I guess I'll move onto the next idea which is maybe ESU is funny with this.

**Comment by the-r3dacted** [comment] 2024-07-23 06:23
Is this a 0x80000003 in xul.dll by chance?

(Check Event Viewer)

**Comment by darkalexis1990** [comment] 2024-07-23 08:31
how can i find this?

**Comment by the-r3dacted** [comment] 2024-07-23 09:50
I forgot to send woops

Win key + R
eventvwr
Enter
Windows Logs
Application
Look for Error Level and find ones for r3dfox.exe

**Comment by Komprogue** [comment] 2024-08-02 18:08
> Is this a 0x80000003 in xul.dll by chance?
> 
> (Check Event Viewer)

I've got an 0x80000003 error in v.127.0.2:

![127 0 2](https://github.com/user-attachments/assets/846ed0b9-2aaa-406a-8582-238dee6fd38a)

But in v.128.0.3 it's another one: 

![128 0 3](https://github.com/user-attachments/assets/e85565c7-db79-4fff-9f83-a2dcccb56a25)

**Comment by the-r3dacted** [comment] 2024-08-06 00:54
Ok, so my guess is Microsoft somehow fucked up DWrite.dll with ESU,

Download this, import the registry file, and move all the files to the r3dfox install directory. Then reboot and try opening r3dfox.
[DWrite.zip](https://github.com/user-attachments/files/16503947/DWrite.zip)

**Comment by Komprogue** [comment] 2024-08-07 02:12
> Download this, import the registry file, and move all the files to the r3dfox install directory. Then reboot and try opening r3dfox. [DWrite.zip](https://github.com/user-attachments/files/16503947/DWrite.zip)

No, it didn't help, unfortunately,

**Comment by the-r3dacted** [comment] 2024-08-07 22:01
Hmm, I'll need to get around to testing with ESU and seeing if I can fix without downgrading Cario.

**Comment by the-r3dacted** [comment] 2024-08-12 13:05
> @K4sum1 it seems to work.
> 
> ![image](https://private-user-images.githubusercontent.com/107497874/350766715-b30542aa-3ec0-4cd5-aa5d-dfdc002f5fc7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NjgxOTEsIm5iZiI6MTcyMzQ2Nzg5MSwicGF0aCI6Ii8xMDc0OTc4NzQvMzUwNzY2NzE1LWIzMDU0MmFhLTNlYzAtNGNkNS1hYTVkLWRmZGMwMDJmNWZjNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMlQxMzA0NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYTE4MDA1Zjg1OWNjNTIxOWFjYzM0MmM3MjhiMDk0Mjc3ZWRkZGZlZTliYjIzNTRiNmExNWZmMWUzMGI3NDlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Y8NUM0IavjUrYufzTh-Gmtu4Y9OhOhp0JWY-pJOT-Q8)

@darkalexis1990 Do you still have those builds? I need them to give to other people to test (download expired)

**Comment by darkalexis1990** [comment] 2024-08-13 11:12
what exactly you want me to send? :)

**Comment by the-r3dacted** [comment] 2024-08-13 15:57
> Try these builds pls
> 
> https://litter.catbox.moe/8wr1wd.7z

This

**Comment by darkalexis1990** [comment] 2024-08-13 20:16
do i have remove the previous with revo unistaller?

**Comment by the-r3dacted** [comment] 2024-08-13 20:17
I mean do you have the installers I gave you that were from that link? I deleted them, and the link expired.

**Comment by darkalexis1990** [comment] 2024-08-13 20:28
sorry i dont have them :(

**Comment by the-r3dacted** [comment] 2024-08-19 04:21
> my ISO is en-US .its a Gen2 ISO release from 9/23

So I found this and tried it https://archive.org/details/win7_gen2 (It's the newest I could find)

And uh it works fine for me wtf

![Screenshot_2024-08-19_00-11-03](https://github.com/user-attachments/assets/69afb3c1-1e36-4a32-a8e3-bb513d6fc291)

**Comment by jonm58** [comment] 2024-08-19 05:22
What are your CPU and GPU?

**Comment by the-r3dacted** [comment] 2024-08-19 06:11
I found a 9/23 Gen2 release and tried it. Still working on my end.

**Comment by the-r3dacted** [comment] 2024-08-19 06:13
@jonm58 I don't think GPU matters here since it's virtualized. You can see their CPU in this pic.

> @K4sum1 it seems to work.
> 
> ![image](https://private-user-images.githubusercontent.com/107497874/350766715-b30542aa-3ec0-4cd5-aa5d-dfdc002f5fc7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNDgyMzEsIm5iZiI6MTcyNDA0NzkzMSwicGF0aCI6Ii8xMDc0OTc4NzQvMzUwNzY2NzE1LWIzMDU0MmFhLTNlYzAtNGNkNS1hYTVkLWRmZGMwMDJmNWZjNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOVQwNjEyMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNTYxMDg0MGZmYzBlMGY5ZGY5NmNlMTVhMGIzN2NiYmI5MDQ5Y2Q2OTQ3ZmUwY2Y4ZThhM2U2ZDc0MDBlMWE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nP5tlf-mqQ8Vd__vaFIYkq4Xdegmgv-6p_6GOF72Su0)

For me, I have 5950X and 2080 Ti, host is MX Linux (I'm using Nouveau because I can btw)

**Comment by lvpha** [comment] 2024-08-22 07:46
Hey @K4sum1 ,

Win 7 ESU (German, partly localized to US-EN) The crash happens when I first launch it. I close the error and launch it again. Then it works perfectly. 

Ryzen 7 5700x/RTX3060.

Btw, I am NOT on a VM. 

I'll create a backup, then proceed with troubleshooting.

**Comment by the-r3dacted** [comment] 2024-08-25 07:54
By chance, can you check if 129.0.2 resolves the issue?

https://github.com/Eclipse-Community/r3dfox/releases/tag/v129.0.2

**Comment by Komprogue** [comment] 2024-08-26 22:43
> By chance, can you check if 129.0.2 resolves the issue?
> 
> https://github.com/Eclipse-Community/r3dfox/releases/tag/v129.0.2

Seems like finally that crash at launching is gone.

**Comment by the-r3dacted** [comment] 2024-08-27 07:44
So it was not Cario, it was this code that only ran if you use the installer.
https://github.com/Eclipse-Community/r3dfox/commit/52ca3f540c66371fb26fbcbafaf2aae3e941c042
I never caught it since I don't use the installer. The downgrade Cairo portable builds working made me think it was Cario and Microsoft broke DWrite or GDI somehow with ESU and since my 2020 update point worked I considered it low priority especially since Cairo is hell to work with. (I initially tried to keep it downgraded for 127)

**Comment by the-r3dacted** [comment] 2024-08-27 07:45
Wait woops, lemme close https://github.com/Eclipse-Community/r3dfox/issues/119 instead

**Comment by the-r3dacted** [comment] 2024-09-16 04:07
Assuming working since no response.

**Closed as completed by the-r3dacted** 2024-09-16 04:07 UTC
