### ISSUE TITLE
The drop-down menu in the DoH settings is not working.

### ISSUE THREAD

**Issue by EDSln** [Eclipse-Community/r3dfox-old#142] opened 2024-07-27 05:11 UTC
In v128.0.2-2 for Vista+, the buttons that show additional DoH settings do not work.
![not naming](https://github.com/user-attachments/assets/cb3a2fc8-036f-48fe-b98c-b7b0513aabf6)

**Comment by the-r3dacted** [comment] 2024-07-27 07:43
When did the issue begin? (Test older versions until you find the first to work)

**Comment by EDSln** [comment] 2024-07-27 08:02
The latest version where it works is Release v128.0-2, it does not work in Release v128.0.2 for Vista+ and Release v128.0.2-2 for Vista+.

**Comment by the-r3dacted** [comment] 2024-07-27 12:06
This might be a 128.0.x bug, I went back to the last commit I built for 128.0-2 but with the tree at 128.0.3 and it still occurs.

**Comment by the-r3dacted** [comment] 2024-07-27 13:06
Huh completely stock 128.0.3 is fine though. This is a weird bug.

**Comment by jonm58** [comment] 2024-07-27 13:17
btw,windows 11 no bug

**Comment by the-r3dacted** [comment] 2024-07-27 13:25
Huh? My build machine is running 10 22H2 and it has this bug.

**Comment by EDSln** [comment] 2024-07-27 13:34
I checked on Win 7, profile is clean, I delete user folders before installing.

**Comment by the-r3dacted** [comment] 2024-07-27 18:47
So disabling MOZ_NORMANDY (telemetry) breaks those options. I'll see if I can find the offending commit.

**Comment by the-r3dacted** [comment] 2024-07-27 23:41
Found the cause, this commit.
https://github.com/Eclipse-Community/r3dfox/commit/e7e5736cb4a14319545bbc1acd07f8db7ad73828
Will be fixed in next version (Probably 128.0.3)

**Comment by the-r3dacted** [comment] 2024-07-29 18:05
https://github.com/Eclipse-Community/r3dfox/releases/tag/v128.0.3

**Closed as completed by the-r3dacted** 2024-07-29 18:05 UTC
