### ISSUE TITLE
Crash Problem

### ISSUE THREAD

**Issue by Cr0nox-F14** [Eclipse-Community/r3dfox-old#154] opened 2024-08-11 17:29 UTC
When I close the browser and reopen it, it crashes and I have to reopen it. It's kind of annoying.

**Comment by the-r3dacted** [comment] 2024-08-12 15:39
Are you using ESU by chance?

**Comment by newbie-461** [comment] 2024-08-15 06:16
I have the same problem (WIN7x64 build 7601.24214.180801)
~~![Untitled](https://github.com/user-attachments/assets/516efca0-fd84-4120-afbf-4be5a79c2529) ~~
~~It looks like caused by _api-ms-win-core-winrt-string-l1-1-0.dll_ missing.~~
copied api-ms-win-core-winrt-l1-1-0.dll api-ms-win-core-winrt-string-l1-1-0.dll(from win8), but still have problem

[PinCurrentAppToTaskbarImpl](https://github.com/Eclipse-Community/r3dfox/blob/ebdf68c15f6c6533b3ebab55602c15e3080ea415/browser/components/shell/nsWindowsShellService.cpp#L1957C2-L1957C2)--> PinCurrentAppToTaskbarWin11 --> Win11LimitedAccessFeatures::Unlock maybe here

**Comment by jonm58** [comment] 2024-08-15 08:11
> I have the same problem (WIN7x64 build 7601.24214.180801) ![Untitled](https://private-user-images.githubusercontent.com/139617217/358133437-516efca0-fd84-4120-afbf-4be5a79c2529.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MDg0MTcsIm5iZiI6MTcyMzcwODExNywicGF0aCI6Ii8xMzk2MTcyMTcvMzU4MTMzNDM3LTUxNmVmY2EwLWZkODQtNDEyMC1hZmJmLTRiZTVhNzljMjUyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQwNzQ4MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNTIwMGQ2ZTgwYzk3ZTJlYjBiNTA3MTY0NDg5OGNkMjEzNmM1OGYzZmNmZjFhNzk2OGJjOGE1MDFmNTU1MmQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DtMdMjBjDTmQGi7L51j0GqZ2j-u55h4IHStkV4Gh6xw)
> 
> It looks like caused by _api-ms-win-core-winrt-string-l1-1-0.dll_ missing.

https://github.com/dotnet/core/issues/6976
https://github.com/tauri-apps/tauri/issues/10624
https://github.com/clowd/Clowd.Squirrel/issues/98
https://github.com/NickeManarin/ScreenToGif/issues/1077

@K4sum1 add api-ms-win-core-winrt-string-l1-1-0.dll for win7

**Comment by newbie-461** [comment] 2024-08-15 11:45
> [dotnet/core#6976](https://github.com/dotnet/core/issues/6976) [tauri-apps/tauri#10624](https://github.com/tauri-apps/tauri/issues/10624) [clowd/Clowd.Squirrel#98](https://github.com/clowd/Clowd.Squirrel/issues/98) [NickeManarin/ScreenToGif#1077](https://github.com/NickeManarin/ScreenToGif/issues/1077)
> 
> @K4sum1 add api-ms-win-core-winrt-string-l1-1-0.dll for win7

Temporary solution for r3dfox-129.0.1-win64

patch xul.dll to disable PinCurrentAppToTaskbar feature
xul.dll file offset+5B2EC90h : 41574156 -> 31C0C390

api-ms-win-core-winrt-*.dll are not needed

**Comment by the-r3dacted** [comment] 2024-08-15 14:31
Can you tell me when this first began? Then I could trace the change, and if I can just delay load or report false when the function is called, that could work.

**Comment by the-r3dacted** [comment] 2024-08-15 14:33
I'm also not sure what the issue is here. It works fine on my 7 without any winrt-* files. Could it be outdated VC++ redist?

**Comment by newbie-461** [comment] 2024-08-15 18:23
Using the installer version, on the "Set Up Shoutcuts" installer page, "On my desktop" checked
it could be reproduced

**Comment by the-r3dacted** [comment] 2024-08-15 18:27
I can't reproduce it.

**Comment by jonm58** [comment] 2024-08-15 23:13
> I'm also not sure what the issue is here. It works fine on my 7 without any winrt-* files. Could it be outdated VC++ redist?

You just need to integrate this dll. That's it.

**Comment by the-r3dacted** [comment] 2024-08-19 04:15
Ok, so this instance should be fixed when 129.0.2 comes out. Any other crash issues go here. https://github.com/Eclipse-Community/r3dfox/issues/125

**Closed as completed by the-r3dacted** 2024-08-19 04:15 UTC
