### ISSUE TITLE
Aero...

### ISSUE THREAD

**Issue by ant1994ant** [Eclipse-Community/r3dfox-old#30] opened 2024-03-23 07:02 UTC
Windows 7 x64 (Aero theme) - Inactive tabs are not visible; when the window is maximized to full screen, the menu bar is cut off.

Maybe it would be better to remove the aero feature and leave the original window interface, as well as the name of the executable file ? (firefox.exe)
![2024-3-23 8-43-32](https://github.com/Eclipse-Community/r3dfox/assets/145537445/fe2a82db-6587-471d-bee0-ad536cb8a029)

**Comment by unter-officer** [comment] 2024-03-23 07:33
Please, remove the aero feature and leave the original window interface as it was in version 122.

**Comment by the-r3dacted** [comment] 2024-03-23 11:44
Duplicate of https://github.com/Eclipse-Community/r3dfox/issues/20

**Closed as completed by the-r3dacted** 2024-03-23 11:44 UTC

**Comment by the-r3dacted** [comment] 2024-07-16 00:40
If anyone is still interested, I realized there already is a method to get the Windows 10 UI on r3dfox on any Windows version.

Go to about:config and set widget.ev-native-controls-patch.override-win-version to 10

![r3dfox win 10 ui on 7](https://github.com/user-attachments/assets/db706ccf-73fe-4b1b-a227-4313b9e317d0)
