### ISSUE TITLE
Is there any plan to support Windows XP SP1/SP2 (x86)?

### ISSUE THREAD

**Issue by EgorKuzevanov** [Eclipse-Community/r3dfox-old#171] opened 2024-08-30 08:23 UTC
Is it planned to add experimental support for 32-bit versions of Windows XP SP1 (released September 9, 2002) and Windows XP SP2 (released August 6, 2004) to r3dfox using **progwrp.dll** wrapper library, as implemented in Supermium? Including SSE-only CPUs (Intel Pentium 3 or AMD Athlon XP level).

**Comment by the-r3dacted** [comment] 2024-08-30 08:49
If it happens, it will be with a custom, similar wrapper that is open source. When or if this happens I have no idea. Also this is duplicate of https://github.com/Eclipse-Community/r3dfox/issues/151

**Closed as completed by the-r3dacted** 2024-08-30 08:49 UTC

**Comment by jonm58** [comment] 2024-08-30 10:38
@K4sum1 
https://github.com/Chuyu-Team/YY-Thunks/issues/80
If your program prompts that the API cannot be found, please use [YY-Thunk](https://github.com/Chuyu-Team/YY-Thunks)'s built-in YY.Depends.Analyzer to scan your application. The scanner will check all missing APIs and compile them into reports, which can greatly reduce the probability of omissions.
