### ISSUE TITLE
problem with set as default browser

### ISSUE THREAD

**Issue by TRX99** [Eclipse-Community/r3dfox-old#40] opened 2024-03-30 00:40 UTC
Hello

set as default browser in settings does not work In version 124.0.2 without Aero. Of course, I also have Firefox 115.9.1esr installed. I don't know if it interferes? But this problem does not exist in Firefox and it does not interfere.

By the way, why are all the versions you provide beta and not a stable version?

_______________________________

My next question is, can you do the same for Google Chrome so that the latest version can be installed on Windows 7? Because another person does this, but the versions he creates do not display the icons, and after 50 days, this problem still exists.

ّFirst issue: https://github.com/win32ss/supermium/issues/218

second issue: https://github.com/win32ss/supermium/issues/429

_________________________

This is also a request that I would like you to make in r3dfox if possible because they could not implement it in Chrome.

issue: https://github.com/win32ss/supermium/issues/302

**Comment by the-r3dacted** [comment] 2024-03-30 16:42
Out of the current releases, can you tell which work and which don't setting default browser?

I'm not going to be making a 7 Chrome. If you want an alternative there is https://github.com/Alex313031/thorium-win7

You could probably userChrome the PDF reader, but yeah that does look better. Adding it to https://github.com/Eclipse-Community/r3dfox/issues/36.

**Comment by TRX99** [comment] 2024-03-31 03:01
> Out of the current releases, can you tell which work and which don't setting default browser?
> 
> I'm not going to be making a 7 Chrome. If you want an alternative there is https://github.com/Alex313031/thorium-win7
> 
> You could probably userChrome the PDF reader, but yeah that does look better. Adding it to Eclipse-Community/r3dfox#3.

I like the version without Aero more, but in the next versions, if possible, please provide both versions so that everyone can choose according to their own taste.

I am very very grateful to you for making such a browser for Windows 7

https://github.com/Eclipse-Community/r3dfox/assets/76468679/0bfbd595-efea-4b4f-b2d4-138d6189630a

**Comment by the-r3dacted** [comment] 2024-03-31 03:07
Before I know it every version will have people asking xyz without theme change, Just userChrome.css out the fog if you hate it so much. Every other difference is just an objective improvement

Make userChrome.css with this code

```
root:
  #TabsToolbar {
    background-image: none !important;
  }
```

Plop in profile folder/chrome and enable legacy styling in about:config

Boom fog gone, now 124 Aero looks like unfucked regular 124.

Also I can't replicate in VM with 124 Aero.

**Comment by wealstarr** [comment] 2024-04-01 09:32
This fix doesn't bring back the titlebar which is non-existant in 124

Would it be possible to compile two binaries, one without chaging anything in the interfece ?

**Comment by unter-officer** [comment] 2024-04-01 18:30
I support **TRX99** and **wealstarr**. Will also repeat my request.

Compile please 2 binaries, one without Aero and with the original window interface as it was in version 122, and one with Aero.

**Comment by the-r3dacted** [comment] 2024-04-02 11:17
So I took a look at trying to add the PDF colors, and I would need to adjust a bunch more colors since the contents bar in Firefox also takes from background color. I don't think it's worth it.

**Comment by the-r3dacted** [comment] 2024-04-16 18:04
Can't reproduce, closing unless others find it to be an issue.

**Closed as completed by the-r3dacted** 2024-04-16 18:04 UTC
