### ISSUE TITLE
i can't play spotify!

### ISSUE THREAD

**Issue by krimnassim** [Eclipse-Community/r3dfox-old#215] opened 2024-11-10 12:17 UTC
why spotify won't play any songs?does r3dfox has drm issue like other browsers?
![Capture](https://github.com/user-attachments/assets/60570efa-eccd-4a0f-9a36-a1811c121d36)

**Comment by jonm58** [comment] 2024-11-11 11:32
DRM (Digital Rights Management) is a copyright protection mechanism. When you try to play content protected by DRM, the website checks if the necessary DRM software is available. Most browsers use [Widevine](https://www.widevine.com/), a DRM technology developed by Google.

r3dfox doesn't have a Widevine license. Therefore, DRM-protected videos or music cannot be played in r3dfox.

**Comment by garry-ut99** [comment] 2024-11-13 10:06
Duplicate of:
- https://github.com/Eclipse-Community/r3dfox/issues/50
- https://github.com/Eclipse-Community/r3dfox/issues/9#issuecomment-2220791064
- https://github.com/Eclipse-Community/r3dfox/issues/133

You can try Luminafox fork, which supports DRM: https://github.com/Eclipse-Community/r3dfox/issues/9#issuecomment-2241725102 / https://github.com/Eclipse-Community/r3dfox/issues/133#issuecomment-2241733629
(but it's no longer developed and the latest version is 128.0.2-rc3)

> jonm58: r3dfox doesn't have a Widevine license.

Yeah, as far I know it costs several thousands of $, too much for alone fork like r3dfox, but not a problem for a big company like Mozilla.

**Closed as completed** 2024-11-18 07:13 UTC
