### ISSUE TITLE
Improve Vista Extended Kernel Support (Fix 0xc0000005 error at launch)

### ISSUE THREAD

**Issue by 4194304** [Eclipse-Community/r3dfox-old#8] opened 2024-01-30 00:29 UTC
As a person who absolutely adores Vista, I like to have decent browsers. The two browsers I know of that exist, I have problems with. Mypal is updated pretty much none of the time, and Supermium is bad from a privacy standpoint to me, since it's based off of Chromium. I found Redfox today, and the main reason why I'm making this is simply this; "Why have One  Core API support but not Extended Kernel support?". I know that this might be a massive undertaking, but if the support for an "extended kernel" is already here for XP, why discard Vista? There's a community of people like me who think that Vista is still great to this day.

Thank you, 4194304

**Comment by the-r3dacted** [comment] 2024-01-30 03:47
> I found Redfox today, and the main reason why I'm making this is simply this; "Why have One Core API support but not Extended Kernel support?". I know that this might be a massive undertaking, but if the support for an "extended kernel" is already here for XP, why discard Vista? There's a community of people like me who think that Vista is still great to this day.

In my test VM, past 112 or so, Firefox does not run, only giving a 0x0000005 error. Therefore r3dfox also gives that error. Some people do have later versions of Firefox working on the extended kernel somehow, and I had one of them test this, and it does run but is apparently super slow and lags the entire machine.

I doubt it would be easy to find whatever commits have done this. There's going to be no oh we did this to break Vista Extended Kernel commit. I've kinda lost interest in the Vista Extended Kernel due to applications just not working for seemingly no reason, especially applications that work just fine on stock Vista. It also seemingly won't be getting more updates, getting close to a year with no updates. Therefore I'm not going out of my way to look for what broke it, but if you find it, I will revert it.

For One Core API, it kinda just works once you have the environment variables, I did nothing for it.

**Comment by 4194304** [comment] 2024-01-30 06:31
Is that only when installing it? Firefox does that and in Michael MJD's video it showed the same error when it installed, but the app functioned just fine. You should probably try it again and see

**Comment by the-r3dacted** [comment] 2024-01-30 06:54
> Is that only when installing it? Firefox does that and in Michael MJD's video it showed the same error when it installed, but the app functioned just fine. You should probably try it again and see

No, I've actually been extracting it. I kinda forgot I fixed the installer running. However this time I tried running the installer and it actually opens. It seems to have the font issue which can be fixed with osver.ini

Not sure what issue that guy I had test it was having, but it ran fine in my VM after this. I am using different build options since I don't want super long build times when prototyping branding, so it could be that idk.

Next release I'll see if I can fix the font issue. I'm not sure how it checks for 7 SP0 (7600) and uses a different font path. I can't find anything relevant searching 7600 with searchfox. Do you have any ideas?

Also I guess I might as well check for what causes the 0x0000005, but it's probably an issue with the kernel as many other apps have breaking issues.

**Comment by 4194304** [comment] 2024-01-30 15:31
That's great! If it works just fine with some help, I think that adding "support" for Redfox with it would be perfect. I think I encountered the font issue with official Firefox a while back (with the extended kernel), and had no idea how to fix it. My possible idea is that you could force it to use the system font if the normal Firefox font fails? I'm a bit unsure about to fix that issue

**Comment by the-r3dacted** [comment] 2024-01-30 17:11
I know what caused the font issue is somewhere in these, but I have no idea where. I tried looking through the issues I would think would be relevant, but I don't see anything that sticks out to me. Maybe you or someone else could find something

https://hg.mozilla.org/mozilla-central/log/d9d5e0e8c2b3c73356fb08d273de233283af1f8a
https://hg.mozilla.org/mozilla-central/log/9e700f1967310803764fc96cfcc4d9b07b0aa501
https://hg.mozilla.org/mozilla-central/log/43a1b07dcefd48b94e2d7a324c98bb516724c7ec
https://hg.mozilla.org/mozilla-central/log/89af6ae2b87f0f27be9a7e2e6ed8269c8568a55a
https://hg.mozilla.org/mozilla-central/log/52d2c9e672d0a0c50af4d6c93cc0239b9e751d18

**Comment by the-r3dacted** [comment] 2024-01-30 17:16
I don't think I will be able to fix the 0xc0000005 error on launch, It happened between 110 and 111, but the last 110 alpha has the bug while release is fine. That is a bit too big of a gap to find an unintended result of some sort of commit or change.

**Comment by the-r3dacted** [comment] 2024-01-30 18:55
I believe I have the font issue fixed, will have to double check first.

**Comment by the-r3dacted** [comment] 2024-01-30 19:56
As far as I know, the font issue is fixed. Making new release now.

**Comment by the-r3dacted** [comment] 2024-01-30 20:02
https://github.com/Eclipse-Community/r3dfox/releases/tag/122.0.1-beta-branded

**Comment by 4194304** [comment] 2024-01-31 02:38
Perfect! I'll test it on a Vista VM and see if it works properly

**Comment by the-r3dacted** [comment] 2024-04-17 12:12
This is a bug with the kernel that I am unlikely to ever figure out the cause of. Just needs to be updated and fixed on their end.

**Closed as completed by the-r3dacted** 2024-04-17 12:12 UTC
Labels: help wanted
